
GET http://localhost:5026

###
GET http://localhost:5026/api/categories

###
GET http://localhost:5026/api/categories?searchValue=electronics

###
POST http://localhost:5026/api/categories
Content-Type: application/json

{
    "name" :"Smart phone",
    "description": "Electronis including shirts, Pants"
}

###
PUT http://localhost:5026/api/categories/9fa1a3fe-fca7-43b3-957f-c781a98d8f96
Content-Type: application/json

{
    "name" :"Goru",
    "description": "BAD "
}

###
DELETE http://localhost:5026/api/categories/03ff5146-05a6-4cf5-99be-31dc6c98f38a
